aws:
  region: ${AWS_REGION}
  bedrock_model: ${BEDROCK_MODEL_NAME}
  s3_kb_id: ${KB_ID}
  access_key: ${AWS_ACCESS_KEY_ID}
  secret_key: ${AWS_SECRET_ACCESS_KEY}
  model_arn:  ${BEDROCK_MODEL_ARN}



agent:
  agent_id: ${AGENT_ID} 
  alias_id: ${ALIAS_ID} 


